### ISSUE TITLE
Support multiple playground pages

### ISSUE THREAD

**Issue by eriklamanna** [willowtreeapps/Playdown#1]
It would be great to just point the tool to a playground and it run through all of the pages in the playground.

**Comment by mrketchup** [comment]
@eriklamanna What is the expected output of a playground with multiple pages? I'm envisioning:
- One file
- Each page is its own section
- At the top is a generated table of contents with links to sections

And in the case of a playground with no pages, it falls back to old standard behavior.

**Comment by eriklamanna** [comment]
To start I'd say 1 page per playground page. Leave it up to the playground writing to make their own TOC. I think down the road having an option to do what you said could be a good command line option.
